{{- if .Values.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reactive-policy.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reactive-policy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "reactive-policy.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
{{- end }}
